### ISSUE TITLE
how can i parse dynamic xml

### ISSUE THREAD

**Issue by kulame** [tafia/quick-xml#486]
i have some dynamic input xml struct.

```xml
<xml>
  <ToUserName><![CDATA[toUser]]></ToUserName>
  <FromUserName><![CDATA[fromUser]]></FromUserName>
  <CreateTime>1348831860</CreateTime>
  <MsgType><![CDATA[text]]></MsgType>
  <Content><![CDATA[this is a test]]></Content>
  <MsgId>1234567890123456</MsgId>
  <MsgDataId>xxxx</MsgDataId>
  <Idx>xxxx</Idx>
</xml>

<xml>
  <ToUserName><![CDATA[toUser]]></ToUserName>
  <FromUserName><![CDATA[fromUser]]></FromUserName>
  <CreateTime>12345678</CreateTime>
  <MsgType><![CDATA[text]]></MsgType>
  <Content><![CDATA[你好]]></Content>
</xml>

<xml>
  <ToUserName><![CDATA[toUser]]></ToUserName>
  <FromUserName><![CDATA[fromUser]]></FromUserName>
  <CreateTime>12345678</CreateTime>
  <MsgType><![CDATA[image]]></MsgType>
  <Image>
    <MediaId><![CDATA[media_id]]></MediaId>
  </Image>
</xml>

<xml>
  <ToUserName><![CDATA[toUser]]></ToUserName>
  <FromUserName><![CDATA[fromUser]]></FromUserName>
  <CreateTime>12345678</CreateTime>
  <MsgType><![CDATA[music]]></MsgType>
  <Music>
    <Title><![CDATA[TITLE]]></Title>
    <Description><![CDATA[DESCRIPTION]]></Description>
    <MusicUrl><![CDATA[MUSIC_Url]]></MusicUrl>
    <HQMusicUrl><![CDATA[HQ_MUSIC_Url]]></HQMusicUrl>
    <ThumbMediaId><![CDATA[media_id]]></ThumbMediaId>
  </Music>
</xml>


```

how can i dynamic deserialize this xml by  quick_xml::de::from_str?

**Comment by kulame** [comment]
i try to deserialize by enum  
 ```rust
#[derive(Serialize, Deserialize, Debug)]
pub struct StandardMessage {
    #[serde(rename = "ToUserName")]
    pub to_user_name: String,
    #[serde(rename = "FromUserName")]
    pub from_user_name: String,
    #[serde(rename = "CreateTime")]
    create_time: u64,
    #[serde(rename = "MsgType")]
    msg_type: String,
    #[serde(rename = "Content")]
    content: String,
    #[serde(rename = "MsgId")]
    msg_id: u64,
    #[serde(rename = "MsgDataId")]
    msg_data_id: Option<String>,
    #[serde(rename = "Idx")]
    idx: Option<i32>,
}

#[derive(Serialize, Deserialize, Debug)]

pub struct ImageReplyMessage {
    #[serde(rename = "$unflatten=ToUserName")]
    to_user_name: String,
    #[serde(rename = "$unflatten=FromUserName")]
    from_user_name: String,
    #[serde(rename = "$unflatten=CreateTime")]
    create_time: i64,
    #[serde(rename = "$unflatten=MsgType")]
    msg_type: String,
    #[serde(rename = "Image")]
    image: Image,
}

#[derive(Serialize, Deserialize, Debug)]
pub enum Xml {
    #[serde(rename = "xml")]
    ImageReplyMessage(ImageReplyMessage),
    #[serde(rename = "xml")]
    StandardMessage(StandardMessage),
}
```

it's ok for parse ImageReplyMessage. but when i try to parse StandardMessage, it raise error 
```bash
thread 'xml::tests::test_standard_message' panicked at 'called `Result::unwrap()` on an `Err` value: Custom("missing field `Image`")', src/xml.rs:153:55
```

**Comment by Mingun** [comment]
First of all, it is an error to rename several fields to the same name (`xml` in your case). Serde should prohibit that, if this code is ever compiled, that is a bug that should be reported upstream.

Secondly, the top-level tag name does not matter, so you will not have `xml` name in your structs. Top-level name is a part of a virtual surrounding struct, not your struct that represents the whole document:
```rust
struct Virtual {
  // Represents the whole `<xml>...<xml>` document
  xml: MyDocumentType,
}
```

It seems that `MsgType` field determines the shape of the XML, so you can use [internally tagged enums](https://serde.rs/enum-representations.html#internally-tagged):

```rust
// rename_all renames variant names which represents a tags in <MsgType>
#[derive(Serialize, Deserialize, Debug, PartialEq)]
#[serde(rename_all = "lowercase", tag = "MsgType")]
pub enum MyDocumentType {
  #[serde(rename_all = "PascalCase")]
  Text {
    // common part
    to_user_name: String,
    from_user_name: String,
    create_time: u64,

    content: String,
    msg_id: Option<u64>,
    msg_data_id: Option<String>,
    idx: Option<i32>,
  },
  #[serde(rename_all = "PascalCase")]
  Image {
    // common part
    to_user_name: String,
    from_user_name: String,
    create_time: u64,

    image: Image,
  },
  #[serde(rename_all = "PascalCase")]
  Music {
    // common part
    to_user_name: String,
    from_user_name: String,
    create_time: u64,

    music: Music,
  },
}

#[derive(Serialize, Deserialize, Debug, PartialEq)]
#[serde(rename_all = "PascalCase")]
pub struct Image {
  pub media_id: String,
}

#[derive(Serialize, Deserialize, Debug, PartialEq)]
#[serde(rename_all = "PascalCase")]
pub struct Music {
  pub title: String,
  pub description: String,
  pub music_url: String,
  #[serde(rename = "HQMusicUrl")]
  pub hq_music_url: String,
  pub thumb_media_id: String,
}
```
Serialization of that structs probably will serialize some tags as attributes, but this will be fixed soon -- I'll make a PR this weekend. The workaround is described [here](https://github.com/tafia/quick-xml/issues/280#issuecomment-1198871958). Also, currently it suffers from #346, but that's also will be fixed in my PR

**Comment by kulame** [comment]
thanks @Mingun 

but i try to follow it , it also raise error message

```bash
---- tests::test_standard_message stdout ----
thread 'tests::test_standard_message' panicked at 'called `Result::unwrap()` on an `Err` value: Custom("missing field `xml`")', src/main.rs:63:55
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
```
my reproduce code is  [https://github.com/kulame/issue486/blob/master/src/main.rs](reproduce code)

```bash
git clone git@github.com:kulame/issue486.git && cd issue486
cargo build && cargo test
```

**Comment by Mingun** [comment]
This is because you try to interpret top-level tag as a field of your document. That is not true -- top-level tag in XML is not a part of the _type_, it is part of _document element_:
```rust
#[derive(Serialize, Deserialize, Debug, PartialEq)]
pub struct Xml {
    pub xml: Message,
}
```
You should deserialize `Message` type directly instead:
```diff
-        let event: Xml = quick_xml::de::from_str(xml).unwrap();
+        let event: Message = quick_xml::de::from_str(xml).unwrap();
```

**Comment by kulame** [comment]
hmm..

i try to use Message to deserilize

it raise 
```bash
thread 'tests::test_standard_message' panicked at 'called `Result::unwrap()` on an `Err` value: Custom("unknown variant `xml`, expected `ImageReplyMessage` or `StandardMessage`")', src/main.rs:63:59
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
```
lol

**Comment by kulame** [comment]
i try to use tag for enum

```rust
#[derive(Serialize, Deserialize, Debug, PartialEq)]
#[serde(rename_all = "lowercase", tag="MsgType")]
pub enum Message {
    #[serde(rename_all = "PascalCase")]
    Image {
        to_user_name: String,
        from_user_name: String,
        create_time: i64,
        image: Image,
    },

    #[serde(rename_all = "PascalCase")]
    Text {
        to_user_name: String,
        from_user_name: String,
    },
}
```

it raise a new exception 
```bash
thread 'tests::test_standard_message' panicked at 'called `Result::unwrap()` on an `Err` value: Custom("invalid type: map, expected a string")', src/main.rs:54:59 
```

**Comment by Mingun** [comment]
Ah, yes, this is broken due to serde flaw, corresponding test is disabled:
https://github.com/tafia/quick-xml/blob/240f2049aec50876b6e13e632120b20cd60a37af/tests/serde-de.rs#L5016-L5030

The reason is that `<element>text</element>` represented as
```json
{
  "element": {
    "$value": "text"
  }
}
```
for serde when use `deserialize_any`, and serde uses `deserialize_any` when deserializes internally tagged enums. So the workaround would be to make a one big struct with all fields, wrapped in `Option`, and then convert it manually to the actual structs:
```rust
impl<'de> Deserialize<'de> for MyDocumentType {
  fn deserialize<D>(deserializer: D) -> Result<Self, D::Error> {
    #[derive(Deserialize, Debug, PartialEq)]
    #[serde(rename_all = "PascalCase")]
    struct MyDocumentTypeImpl {
      // common part
      to_user_name: String,
      from_user_name: String,
      create_time: u64,
      msg_type: String,

      // <MsgType>text</MsgType> fields
      content: Option<String>,
      msg_id: Option<u64>,
      msg_data_id: Option<String>,
      idx: Option<i32>,

      // <MsgType>image</MsgType> fields
      image: Option<Image>,

      // <MsgType>music</MsgType> fields
      music: Option<Music>,
    }
    let data = MyDocumentTypeImpl::deserialize(deserializer)?;
    // construct Self from `data`
  }
}
```

**Comment by kulame** [comment]
hmm...  not very elegant....   thanks a lot

**Comment by darkprokoba** [comment]
Similar problem here, only the discriminator in my case is inside an attribute instead of in a child element...

**Comment by Mingun** [comment]
Because of how `serde` is worked we cannot fix the issue with internally tagged enums from quick-xml side.
